// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/assess_student.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssessStudentService_AssessStudent_FullMethodName = "/proto.AssessStudentService/AssessStudent"
)

// AssessStudentServiceClient is the client API for AssessStudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssessStudentServiceClient interface {
	AssessStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*AssessmentResponse, error)
}

type assessStudentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssessStudentServiceClient(cc grpc.ClientConnInterface) AssessStudentServiceClient {
	return &assessStudentServiceClient{cc}
}

func (c *assessStudentServiceClient) AssessStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*AssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssessmentResponse)
	err := c.cc.Invoke(ctx, AssessStudentService_AssessStudent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssessStudentServiceServer is the server API for AssessStudentService service.
// All implementations must embed UnimplementedAssessStudentServiceServer
// for forward compatibility.
type AssessStudentServiceServer interface {
	AssessStudent(context.Context, *Student) (*AssessmentResponse, error)
	mustEmbedUnimplementedAssessStudentServiceServer()
}

// UnimplementedAssessStudentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssessStudentServiceServer struct{}

func (UnimplementedAssessStudentServiceServer) AssessStudent(context.Context, *Student) (*AssessmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssessStudent not implemented")
}
func (UnimplementedAssessStudentServiceServer) mustEmbedUnimplementedAssessStudentServiceServer() {}
func (UnimplementedAssessStudentServiceServer) testEmbeddedByValue()                              {}

// UnsafeAssessStudentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssessStudentServiceServer will
// result in compilation errors.
type UnsafeAssessStudentServiceServer interface {
	mustEmbedUnimplementedAssessStudentServiceServer()
}

func RegisterAssessStudentServiceServer(s grpc.ServiceRegistrar, srv AssessStudentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAssessStudentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssessStudentService_ServiceDesc, srv)
}

func _AssessStudentService_AssessStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessStudentServiceServer).AssessStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssessStudentService_AssessStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessStudentServiceServer).AssessStudent(ctx, req.(*Student))
	}
	return interceptor(ctx, in, info, handler)
}

// AssessStudentService_ServiceDesc is the grpc.ServiceDesc for AssessStudentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssessStudentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AssessStudentService",
	HandlerType: (*AssessStudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssessStudent",
			Handler:    _AssessStudentService_AssessStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/assess_student.proto",
}
