apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventsservice
  template:
    metadata:
      labels:
        app: eventsservice
    spec:
      containers:
        - name: eventsservice
          image: omersadikovic/eventsservice:latest
          env:
            - name: MONGODB_CONNECTION_STRING
              value: "mongodb://mongodb-clusterip-srv:27017"
            - name: JWT_KEY
              value: "YcxjOMewdFfeZFQm5iGAYxTjR23Z93rLbyZucty3"
            - name: JWT_ISSUER
              value: "http://nannies-clusterip-srv:8080"
            - name: JWT_AUDIENCES
              value: "http://nannies-clusterip-srv:8080,http://students-clusterip-srv:8080,http://events-clusterip-srv:8080"
            - name: EVENTS_BASE_URL
              value: "http://events-clusterip-srv:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: events-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: eventsservice
  ports:
  - name: eventsservice
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: plafromgrpc
    protocol: TCP
    port: 666
    targetPort: 666