apiVersion: v1
kind: Service
metadata:
  name: eventsnpservice-srv
spec:
  type: NodePort
  selector:
    app: eventsservice
  ports:
    - name: eventsservice
      protocol: TCP
      port: 8080
      targetPort: 8080